<?php

define('RECAT_CORE_FILE_SALT', 'Y61N7a-[!S4c.h[F$%O6$wJW/5+,S3=(@obTl$P(JuI=Q$Tr[OI3.*?(2LX@y0 +');

function recat_core_schema_alter(&$schema) {
    $schema['file_managed']['fields']['hash'] = array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => false,
    );
}

function recat_core_menu() {
    $items = array();
    $items['admin/config/recat'] = array(
        'title' => t('Recat'),
        'position' => 'right',
        'weight' => -100,
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array('administer site configuration'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );

    return $items;
}

function recat_core_library() {
    $path = drupal_get_path('module', 'recat_core');
    $libraries['recat_core_angularjs'] = array(
        'title' => 'Recat Core AngularJs',
        'version' => '1.3.16',
        'js' => array(
            $path . '/js/vendor/angular.min.js' => array('type' => 'file'),
        ),
    );

    return $libraries;
}

function recat_core_file_insert($file) {
    if (!isset($file->fid)) {
        return;
    }

    _recat_core_save_hash_for_fid($file->fid);
}

function recat_core_wysiwyg_editor_settings_alter(&$settings, $context) {
    if ($context['profile']->editor !== 'ckeditor') {
        return false;
    }

    $settings['contentsCss'] = sprintf(
        '%s%s/design/css/ckeditor.css', base_path(), drupal_get_path('theme', 'recat'));

    $settings['customConfig'] = sprintf(
        '%s%s/ckeditor/config.js', base_path(), drupal_get_path('theme', 'recat'));
}

function _recat_core_get_pager_build($quantity = 10) {
    return array(
        '#theme' => 'pager',
        '#tags' => array(t('first'), t('prev'), null, t('next'), t('last')),
        '#quantity' => $quantity,
    );
}

function _recat_core_save_hash_for_fid($fid, $hash = null) {
    return db_update('file_managed')
        ->fields(array(
            'hash' => $hash === null ? _recat_core_generate_hash_for_fid($fid) : $hash,
        ))
        ->condition('fid', $fid)
        ->execute();
}

function _recat_core_generate_hash_for_fid($fid) {
    return md5(RECAT_CORE_FILE_SALT . $fid);
}