<?php

define('RECAT_NEWS_TAGS_VOCABULARY_NAME', 'news_tags');
define('RECAT_NEWS_CATEGORIES_VOCABULARY_NAME', 'news_categories');

function recat_news_menu() {
    $items = array();
    $items['admin/config/recat/news'] = array(
        'title' => t('News settings'),
        'description' => t('Change the different news settings.'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('recat_news_admin'),
        'access arguments' => array('administer site configuration'),
        'file' => 'recat_news.admin.inc',
    );

    $items[_recat_news_get_url()] = array(
        'title' => 'News',
        'title callback' => 'recat_news_year_page_title',
        'page callback' => 'recat_news_year_page',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
        'file' => 'recat_news.pages.inc',
    );

    return $items;
}

function recat_news_menu_alter(&$items) {
    $items['taxonomy/term/%taxonomy_term']['page callback'] = 'recat_news_taxonomy_page';
    $items['taxonomy/term/%taxonomy_term']['module'] = 'recat_news';
    $items['taxonomy/term/%taxonomy_term']['file'] = 'recat_news.pages.inc';
    $items['taxonomy/term/%taxonomy_term']['file path'] = drupal_get_path('module', 'recat_news');
}

function recat_news_theme() {
    return array(
        'recat_news_listing' => array(
            'template' => 'templates/listing',
            'variables' => array(
                'title' => null,
                'teasers' => array(),
                'item_per_line' => 3,
            ),
        ),
        'recat_news_latest_news' => array(
            'template' => 'templates/latest-news',
            'variables' => array(
                'teasers' => array(),
            ),
        ),
        'recat_news_tags' => array(
            'template' => 'templates/tags',
            'variables' => array(
                'tags' => array(),
            ),
        ),
        'recat_news_categories' => array(
            'template' => 'templates/categories',
            'variables' => array(
                'categories' => array(),
            ),
        ),
        'recat_news_years' => array(
            'template' => 'templates/years',
            'variables' => array(
                'years' => array(),
            ),
        ),
        'recat_news_teaser' => array(
            'template' => 'templates/teaser',
            'variables' => array(
                'image' => null,
                'post_date' => null,
                'title' => null,
                'content' => null,
                'cta' => null,
                'url' => null,
            ),
        ),
    );
}

function recat_news_block_info() {
    $blocks = array();
    $blocks['recat_news'] = array(
        'info' => t('News listing'),
        'cache' => DRUPAL_NO_CACHE,
    );

    $blocks['recat_news_latest'] = array(
        'info' => t('Latest news'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => '<front>',
    );

    $blocks['recat_news_tags'] = array(
        'info' => t('News tags'),
        'cache' => DRUPAL_CACHE_PER_ROLE
    );

    $blocks['recat_news_categories'] = array(
        'info' => t('News categories'),
        'cache' => DRUPAL_CACHE_PER_ROLE
    );

    $blocks['recat_news_years'] = array(
        'info' => t('News years'),
        'cache' => DRUPAL_CACHE_PER_ROLE
    );

    return $blocks;
}

function recat_news_block_configure($delta = '') {
    switch ($delta) {
        case 'recat_news':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_configure($delta);
        case 'recat_news_latest':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_latest_configure($delta);
        case 'recat_news_tags':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_tags_configure($delta);
        case 'recat_news_categories':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_categories_configure($delta);
        case 'recat_news_years':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_years_configure($delta);

    }
}

function recat_news_block_save($delta = '', $edit = array()) {
    switch ($delta) {
        case 'recat_news':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_save($edit, $delta);
        case 'recat_news_latest':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_latest_save($edit, $delta);
        case 'recat_news_tags':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_tags_save($edit, $delta);
        case 'recat_news_categories':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_categories_save($edit, $delta);
        case 'recat_news_years':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return _recat_news_block_years_save($edit, $delta);

    }
}

function recat_news_block_view($delta = '') {
    switch ($delta) {
        case 'recat_news':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return array(
                'title' => '<none>',
                'content' => _recat_news_block_view($delta),
            );
        case 'recat_news_latest':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return array(
                'content' => _recat_news_block_latest_view($delta),
            );
        case 'recat_news_tags':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return array(
                'content' => _recat_news_block_tags_view($delta),
            );
        case 'recat_news_categories':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return array(
                'content' => _recat_news_block_categories_view($delta),
            );
        case 'recat_news_years':
            module_load_include('blocks.inc', 'recat_news', 'recat_news');
            return array(
                'content' => _recat_news_block_years_view($delta),
            );
    }
}

function recat_news_image_default_styles() {
    $styles = array();
    $styles['recat_news'] = array(
        'label' => 'News (610x408)',
        'name' => 'recat_news',
        'storage' => IMAGE_STORAGE_NORMAL,
        'effects' => array(
            array(
                'name' => 'image_scale_and_crop',
                'data' => array(
                    'width' => 610,
                    'height' => 408,
                    'upscale' => 1,
                ),
                'weight' => 0,
            ),
        ),
    );

    $styles['recat_news_teaser'] = array(
        'label' => 'News teaser (370x250)',
        'name' => 'recat_news_teaser',
        'storage' => IMAGE_STORAGE_NORMAL,
        'effects' => array(
            array(
                'name' => 'image_scale_and_crop',
                'data' => array(
                    'width' => 370,
                    'height' => 250,
                    'upscale' => 1,
                ),
                'weight' => 0,
            ),
        ),
    );

    return $styles;
}

function recat_news_preprocess_page(&$variables) {
    if (_recat_news_get_url() === arg(0) . '/%') {
        $variables['is_recat_news'] = true;
    }

    $term = menu_get_object('taxonomy_term', 2);
    if (!$term) {
        return;
    }

    if (!_recat_news_is_taxonomy_page($term)) {
        return;
    }

    $term->is_news = true;
    $variables['term'] = $term;
}

function _recat_news_get_nodes($limit = null, $usePager = false, $order_by = 'created', $order_direction = 'DESC', $conditions = array()) {
    global $language;

    $query = db_select('node', 'n');
    if ($usePager) {
        $query = $query->extend('PagerDefault');
    }

    $query
        ->fields('n', array('nid', 'created'))
        ->condition('status', 1)
        ->condition('language', $language->language)
        ->condition('type', 'news')
        ->orderBy($order_by, $order_direction)
        ->addTag('node_access');

    foreach ($conditions as $condition) {
        $query->condition($condition['column'], $condition['value'], $condition['operator']);
    }

    if ($usePager && $limit) {
        $query->limit($limit);
    } else if ($limit) {
        $query->range(0, $limit);
    }

    return $query->execute()->fetchAllAssoc('nid');
}

function _recat_news_get_tags() {
    return _recat_news_get_terms(RECAT_NEWS_TAGS_VOCABULARY_NAME);
}

function _recat_news_get_categories() {
    return _recat_news_get_terms(RECAT_NEWS_CATEGORIES_VOCABULARY_NAME);
}

function _recat_news_get_terms($vocabulary_name) {
    $tags = array();
    $vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_name);

    if (!$vocabulary) {
        return $tags;
    }

    $tags = taxonomy_get_tree($vocabulary->vid, 0, 1);
    if (!$tags) {
        return $tags;
    }

    if (module_exists('i18n_taxonomy')) {
        $tags = i18n_taxonomy_localize_terms($tags);
    }

    return $tags;
}

function _recat_news_get_count_by_term($term) {
    global $language;

    $query = db_select('node', 'n');

    $query
        ->fields('n', array('nid'))
        ->condition('n.status', 1)
        ->condition('n.language', $language->language)
        ->condition('n.type', 'news')
        ->addTag('node_access');

    $query->join('field_data_field_news_category', 'category', 'category.entity_id = n.nid');

    $query
        ->condition('category.entity_type', 'node')
        ->condition('category.field_news_category_tid', $term->tid);

    return $query->execute()->rowCount();
}

function _recat_news_get_teaser_view($node, $image_style = 'thumbnail', $date_format = 'medium', $max_chars = 150) {
    $node_wrapper = entity_metadata_wrapper('node', $node);

    $teaser = $node_wrapper->field_teaser->value();
    $image = $node_wrapper->field_image->value();

    return array(
        '#theme' => 'recat_news_teaser',
        '#image' => theme_image_style(array(
            'style_name' => $image_style,
            'path' => $image['uri'],
            'width' => $image['width'],
            'height' => $image['height'],
            'title' => $image['title'],
            'alt' => $image['alt'],
            'attributes' => array(
                'class' => array('image'),
            ),
        )),
        '#post_date' => format_date($node->created, $date_format),
        '#title' => $node_wrapper->title->value(),
        '#content' => truncate_utf8($teaser, $max_chars, true, true),
        '#cta' => _hs_resource_get('recat_news.teaser.read_more', 'plain', null, false),
        '#url' => node_uri($node),
    );
}

function _recat_news_get_pager_build() {
    return array(
        '#theme' => 'pager',
        '#tags' => array(t('first'), t('prev'), null, t('next'), t('last')),
        '#quantity' => 10,
    );
}

function _recat_news_get_settings($key = 'recat_news') {
    return variable_get($key, false);
}

function _recat_news_is_taxonomy_page($term) {
    return $term->vocabulary_machine_name === RECAT_NEWS_TAGS_VOCABULARY_NAME
        || $term->vocabulary_machine_name === RECAT_NEWS_CATEGORIES_VOCABULARY_NAME;
}

function _recat_news_get_url($year = '%') {
    return sprintf('recat_news/%s', $year);
}