<?php

function recat_blocks_theme() {
    return array(
        'recat_blocks_headliner' => array(
            'template' => 'templates/headliner',
            'variables' => array(
                'image_url' => null,
                'title' => null,
                'content' => null,
                'cta' => null,
                'url' => null,
            ),
        ),
        'recat_blocks_quick_access' => array(
            'template' => 'templates/quick-access',
            'variables' => array(
                'boxes' => array(),
            ),
        ),
        'recat_blocks_quick_access_box' => array(
            'template' => 'templates/quick-access-box',
            'variables' => array(
                'title' => '',
                'content' => '',
                'icon' => '',
                'url' => '',
                'more_info' => '',
            ),
        ),
        'recat_blocks_facts' => array(
            'template' => 'templates/facts',
            'variables' => array(
                'facts' => array(),
            ),
        ),
    );
}

function recat_blocks_block_info() {
    $blocks = array();
    $blocks['recat_blocks_headliner'] = array(
        'info' => t('Headliner'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => '<front>',
    );

    $blocks['recat_blocks_quick_access'] = array(
        'info' => t('Quick access'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => '<front>',
    );

    $blocks['recat_blocks_facts'] = array(
        'info' => t('Facts'),
        'cache' => DRUPAL_CACHE_PER_ROLE,
        'visibility' => BLOCK_VISIBILITY_LISTED,
        'pages' => '<front>',
    );

    return $blocks;
}

function recat_blocks_block_configure($delta = '') {
    switch ($delta) {
        case 'recat_blocks_headliner':
            module_load_include('headliner.inc', 'recat_blocks', 'includes/recat_blocks');
            return _recat_blocks_headliner_configure($delta);
        case 'recat_blocks_quick_access':
            module_load_include('quick_access.inc', 'recat_blocks', 'includes/recat_blocks');
            return _recat_blocks_quick_access_configure($delta);
        case 'recat_blocks_facts':
            module_load_include('facts.inc', 'recat_blocks', 'includes/recat_blocks');
            return _recat_blocks_facts_configure($delta);

    }
}

function recat_blocks_block_save($delta = '', $edit = array()) {
    switch ($delta) {
        case 'recat_blocks_headliner':
            module_load_include('headliner.inc', 'recat_blocks', 'includes/recat_blocks');
            return _recat_blocks_headliner_save($edit, $delta);
        case 'recat_blocks_quick_access':
            module_load_include('quick_access.inc', 'recat_blocks', 'includes/recat_blocks');
            return _recat_blocks_quick_access_save($edit, $delta);
        case 'recat_blocks_facts':
            module_load_include('facts.inc', 'recat_blocks', 'includes/recat_blocks');
            return _recat_blocks_facts_save($edit, $delta);

    }
}

function recat_blocks_block_view($delta = '') {
    switch ($delta) {
        case 'recat_blocks_headliner':
            module_load_include('headliner.inc', 'recat_blocks', 'includes/recat_blocks');
            return array(
                'title' => '<none>',
                'content' => _recat_blocks_headliner_view($delta),
            );
        case 'recat_blocks_quick_access':
            module_load_include('quick_access.inc', 'recat_blocks', 'includes/recat_blocks');
            return array(
                'content' => _recat_blocks_quick_access_view($delta),
            );
        case 'recat_blocks_facts':
            module_load_include('facts.inc', 'recat_blocks', 'includes/recat_blocks');
            return array(
                'content' => _recat_blocks_facts_view($delta),
            );
    }
}

function _recat_blocks_get_settings($key) {
    return variable_get($key, false);
}

function _recat_blocks_get_nodes($type = null) {
    $language = language_default();

    $query = db_select('node', 'n');
    $query
        ->fields('n', array('nid', 'title'))
        ->condition('status', 1)
        ->condition('language', $language->language)
        ->orderBy('title')
        ->addTag('node_access');

    if ($type) {
        $query->condition('type', $type);
    }

    return $query->execute()->fetchAllAssoc('nid');
}

function _recat_blocks_handle_managed_file($previous_file, $new_file) {
    if ($previous_file === $new_file) {
        return false;
    }

    if ($file = file_load($previous_file)) {
        file_usage_delete($file, 'recat_blocks');
        file_delete($file);
    }

    if ($file = file_load($new_file)) {
        $file->status = FILE_STATUS_PERMANENT;

        file_save($file);
        file_usage_add($file, 'recat_blocks', 'block', $file->fid);
    }
}